version: "3.9"

services:
  database:
    image: postgres:alpine
    container_name: dtmoney-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dtmoney
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: dtmoney-backend
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

# mapping volumes
volumes:
  pgdata:
    driver: local
